import pandas as pd
import re
import nltk
from nltk.corpus import stopwords
import glob

# Ensure stopwords are downloaded
try:
    nltk.data.find('corpora/stopwords')
except LookupError:
    nltk.download('stopwords')

def clean_text(text):
    """
    Clean review text by removing special characters, emojis, and normalizing case.
    """
    if pd.isna(text):
        return ""
    
    text = str(text).lower()
    # Remove URLs
    text = re.sub(r'http\S+|www\S+|https\S+', '', text, flags=re.MULTILINE)
    # Remove user tags and hashtags
    text = re.sub(r'\@\w+|\#', '', text)
    # Remove punctuation and special characters
    text = re.sub(r'[^\w\s]', ' ', text)
    # Remove numbers
    text = re.sub(r'\d+', '', text)
    # Remove extra whitespace
    text = re.sub(r'\s+', ' ', text).strip()
    
    return text

def remove_stopwords(text):
    """
    Remove Indonesian stopwords.
    """
    stop_words = set(stopwords.words('indonesian'))
    
    # Add custom stopwords relevant to app reviews that don't add much meaning
    custom_stopwords = {'aplikasi', 'app', 'nya', 'yg', 'di', 'ke', 'dari', 'ini', 'itu', 'dan', 'atau', 'sangat', 'sekali', 'banget', 'bgt', 'ya', 'aja'}
    stop_words.update(custom_stopwords)
    
    words = text.split()
    filtered_words = [w for w in words if w not in stop_words and len(w) > 2]
    return " ".join(filtered_words)

def classify_sentiment(text, score):
    """
    Classify sentiment based on text lexicon and fallback to Play Store rating score.
    """
    positive_words = {'bagus', 'mantap', 'keren', 'suka', 'terbaik', 'mudah', 'membantu', 'cepat', 'lancar', 'aman', 'oke', 'good', 'puas', 'bermanfaat', 'praktis', 'rekomendasi', 'jos', 'top', 'kece', 'gampang'}
    negative_words = {'jelek', 'kecewa', 'buruk', 'error', 'lemot', 'susah', 'gagal', 'lambat', 'penipu', 'tipu', 'rugi', 'sampah', 'parah', 'hancur', 'bintang', 'tolong', 'perbaiki', 'update', 'login', 'kendala', 'masalah', 'verifikasi', 'lelet', 'ribet', 'bingung', 'tolol', 'bodoh', 'babi', 'anjing'}

    if pd.isna(text):
        text = ""
    words = set(str(text).lower().split())

    pos_count = len(words.intersection(positive_words))
    neg_count = len(words.intersection(negative_words))

    if pos_count > neg_count:
        return 'Positive'
    elif neg_count > pos_count:
        return 'Negative'
    else:
        # Fallback to score
        if score >= 4:
            return 'Positive'
        elif score == 3:
            return 'Neutral'
        else:
            return 'Negative'

def classify_sentiment_indobert(texts, nlp_pipeline):
    """
    Classify a list of texts using an IndoBERT pipeline built in Transformers.
    Maps labels like 'positive'/'LABEL_2' to our standard ['Positive', 'Negative', 'Neutral'].
    """
    if not texts:
        return []
        
    results = nlp_pipeline(texts)
    mapped_results = []
    
    for res in results:
        label = str(res.get('label', '')).lower()
        if 'pos' in label or 'label_2' in label:
            mapped_results.append('Positive')
        elif 'neg' in label or 'label_0' in label:
            mapped_results.append('Negative')
        else:
            mapped_results.append('Neutral')
            
    return mapped_results

def preprocess_dataframe(df):
    """
    Process a pandas DataFrame of raw reviews directly.
    """
    df = df.copy()
    
    # Apply sentiment classification
    df['sentiment'] = df.apply(lambda row: classify_sentiment(row['content'], row['score']), axis=1)
    
    # Clean textual content
    df['clean_content'] = df['content'].apply(clean_text)
    df['keywords'] = df['clean_content'].apply(remove_stopwords)
    
    return df

def preprocess_data():
    """
    Find the generated CSV file, load it, process it, and save the result.
    """
    # Find the latest CSV file generated by the scraper
    csv_files = glob.glob('playstore_reviews_*.csv')
    csv_files = [f for f in csv_files if not f.startswith('processed_')]
    
    if not csv_files:
        print("Error: No raw CSV file found. Please run scraper.py first.")
        return None
        
    latest_file = max(csv_files, key=lambda x: x.split('_')[-1]) # rudimentary way to get newest if multiple
    print(f"Memproses file: {latest_file}")
    
    df = pd.read_csv(latest_file)
    print(f"Total rows: {len(df)}")
    
    df = preprocess_dataframe(df)
    
    # Save the processed dataframe
    output_filename = f"processed_{latest_file}"
    df.to_csv(output_filename, index=False)
    
    print(f"Selesai! Data bersih disimpan ke: {output_filename}")
    
    # Print brief summary
    print("\nRingkasan Sentimen:")
    print(df['sentiment'].value_counts())
    
    return df

if __name__ == "__main__":
    df_processed = preprocess_data()
    if df_processed is not None:
        print("\nPreview data bersih:")
        print(df_processed[['score', 'sentiment', 'clean_content', 'keywords']].head())
